### PR TITLE
Add React 0.14 support

### PR DESCRIPTION
**Pull request by koistya**
- [x] Remove dependency on `ReactDOM.findDOMNode(...)` from `react-dom`
- [x] Ise `ReactDOM.renderToStaticMarkup(...)` from `react-dom/server` module

### CODE REVIEW

**Comment by Merri** [comment]
Thanks for contributing! With a quick look the code you provided won't run on server side environment, which is where setting noscript and IE conditional comments to the rendered HTML make sense.

If a client-only lazy loading is wanted then a separate, much simpler component could be added for that purpose. You don't need to care about noscript stuff at all if code runs client only.

**Comment by koistya** [comment]
Ah, I see.. then, can you make sure that `react-dom/server` is only required during server-side rendering? Yet, removing dependency on `react-dom` findDOMNode(..) is also good idea.

**Comment by Merri** [comment]
Yes, findDOMNode can be replaced with the new React 0.14 way of referencing elements (giving direct DOM element if I recall correctly).

But dependency on `react-dom/server` can't be removed. It is necessary for the initial client render where React checks that what was rendered to HTML server-side matches perfectly with what is at client-side. It simply makes no sense to make it in any other way.

In general I think this is one case where the added separation in React 0.14 causes unnecessary extra confusion by calling it `react-dom/server` when it is completely plausible to need some of the stuff client-side, too. I'd rather call it `react-dom/universal`, but then again that could confuse people in a different way. Maybe it is possible to get only `renderToStaticMarkup` somehow in import/require, but I don't have the interest to investigate that right now.

**Comment by koistya** [comment]
Maybe it will make sense to have two versions of this library one for the client, and another for the server.. e.g.

```js
// on the server
import { Lazy } from 'react-lazy/server';
```

The client-side bundle will reference `react-lazy` and the server-side bundle will reference `react-lazy/server`.

**Comment by Merri** [comment]
That is exactly the case that won't work. If it is a different component that works in a different way, then React will crash/complain about it and you have a broken render. The entire point is to run the exact same universal code on both client and server side.

Attempting to hack around that issue will only cause both unnecessary complexity and a headache.

Instead, it is better to provide a lightweight client only component for those that are not working with universal rendering.

**Comment by koistya** [comment]
@Merri check my latest commit! It just removes a dependency on `findDOMNode(..)` and uses `.renderToStaticMarkup(..)` from `react-dom/server` to remove the warning about this method being deprecated in the core `react` module.

**Comment by Merri** [comment]
I started to take a look at things and I can't accept this pull request: tests need to be updated as well, which lead to updating package.json, which lead to new deps incompatible with my old Node and npm, which lead to updating Node and npm, which all eventually break jsdom / contextify so I have to spend time on fixing the test system or figuring a new way to test this while remaining compatible with Windows (which is what I dev on).

It is sad that a seemingly simple version jump of React can get into such a snowball effect.

**Comment by Merri** [comment]
v0.1.0 released.

**Pull request closed without merging**
